name: Supabase Migrate

on:
  workflow_call:
    inputs:
      project_id:
        required: true
        type: string
    outputs:
      status: ${{ steps.migration_status.outputs.status }}
    secrets:
      access_token:
        required: true

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.access_token }}

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase project
        run: supabase link --project-ref ${{ inputs.project_id }}

      - name: Push database changes
        run: supabase db push

      - id: migration_status
        name: Migration status
        run: echo "status=$(supabase migration list)" >> "$GITHUB_OUTPUT"
